#!/usr/bin/env python3
"""
Audit C9 : Category B — noms communs anglais restants qui n'ont pas de
suffixe caractéristique (traités dans C8).

Critères pour être suspect :
- concept non_classifie
- label single-word sans accent français
- mot EN dans notre wordlist de noms communs anglais
- ISBE entry primaire non traduite (label_fr == mot)
- PAS dans la liste FR safe (déjà français)
- PAS un nom propre biblique (transliterations)

Les mots FR=EN identiques sont listés à part pour info.
"""
import json
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')

ROOT = Path(__file__).resolve().parent.parent
DICT_DIR = ROOT / "uploads" / "dictionnaires"
AUDIT_DIR = ROOT / "work" / "audit"
OUT_JSON = AUDIT_DIR / "isbe-c9-cat-b.json"
OUT_MD = AUDIT_DIR / "isbe-c9-cat-b.md"

# Liste de noms communs anglais fréquents (du Général Service List)
# Ce sont des mots qu'on veut trouver et traduire
ENGLISH_COMMON_NOUNS = {
    # A
    'abase', 'abate', 'abhor', 'abide', 'about', 'above', 'abroad', 'abuse',
    'abyss', 'accursed', 'adder', 'add', 'advent', 'adversary', 'affinity',
    'afraid', 'after', 'afterward', 'afternoon', 'again', 'against', 'age',
    'ahead', 'aid', 'alarm', 'alien', 'alike', 'alive', 'alley', 'all',
    'allied', 'allies', 'allow', 'alloy', 'ally', 'almighty', 'almond',
    'almost', 'alms', 'alone', 'aloft', 'along', 'aloud', 'alphabet', 'already',
    'also', 'altar', 'always', 'amber', 'amen', 'amid', 'amity', 'among',
    'amount', 'ancestor', 'anchor', 'ancient', 'anew', 'anger', 'angle',
    'angry', 'animal', 'anise', 'ankle', 'annals', 'annex', 'annoy',
    'annual', 'anoint', 'another', 'ant', 'antelope', 'antichrist', 'antidote',
    'antiquity', 'anvil', 'anxiety', 'any', 'apart', 'ape', 'apiece',
    'apostle', 'apparel', 'appeal', 'appetite', 'apple', 'apply', 'appoint',
    'approach', 'approve', 'apron', 'aqueduct', 'arch', 'area', 'arena',
    'argue', 'aright', 'arise', 'arithmetic', 'arm', 'armed', 'armlet',
    'armor', 'armory', 'army', 'around', 'arrange', 'array', 'arrest',
    'arrival', 'arrive', 'arrogant', 'arrow', 'art', 'article', 'artificer',
    'ascend', 'ash', 'ashamed', 'ashes', 'aside', 'ask', 'asleep', 'ass',
    'assault', 'assay', 'assembly', 'assent', 'assign', 'assist', 'astray',
    'athlete', 'atonement', 'attack', 'attain', 'attempt', 'attend', 'attire',
    'aunt', 'avail', 'avenge', 'aware', 'away', 'awe', 'axe',
    # B
    'back', 'backbone', 'backslide', 'bad', 'badge', 'bag', 'bake', 'bald',
    'bale', 'ball', 'balm', 'balsam', 'band', 'bank', 'banner', 'banquet',
    'baptism', 'baptist', 'baptize', 'bar', 'barb', 'barbarian', 'bard',
    'bare', 'barefoot', 'bargain', 'barley', 'barn', 'barrel', 'base',
    'bashful', 'basin', 'basket', 'bastard', 'bat', 'bath', 'battle', 'bay',
    'beach', 'beacon', 'bead', 'beak', 'beam', 'bean', 'bear', 'beard',
    'beast', 'beaten', 'beautiful', 'beauty', 'beckon', 'become', 'bed',
    'bee', 'beef', 'beer', 'beetle', 'beget', 'beggar', 'begin', 'beguile',
    'behalf', 'behave', 'behind', 'behold', 'being', 'believe', 'bell',
    'belly', 'belong', 'beloved', 'below', 'belt', 'bench', 'bend', 'beneath',
    'benefit', 'berry', 'beseech', 'beside', 'besides', 'besiege', 'best',
    'bestow', 'bet', 'betray', 'better', 'between', 'bewail', 'beware',
    'beyond', 'bible', 'bid', 'big', 'bill', 'bind', 'birch', 'bird', 'birth',
    'bishop', 'bit', 'bite', 'bitter', 'black', 'blade', 'blame', 'blast',
    'blaze', 'bleach', 'bleed', 'blemish', 'blend', 'bless', 'blessed',
    'blind', 'blood', 'bloody', 'blossom', 'blot', 'blow', 'blue', 'board',
    'boast', 'boat', 'body', 'boil', 'bold', 'bond', 'bondage', 'bone',
    'bonnet', 'book', 'booth', 'booty', 'border', 'born', 'bosom', 'both',
    'bottle', 'bottom', 'bough', 'bound', 'bow', 'bowels', 'bowl', 'box',
    'boy', 'brace', 'bracelet', 'brake', 'bramble', 'branch', 'brand', 'brass',
    'brave', 'bread', 'breach', 'break', 'breast', 'breath', 'brick', 'bride',
    'bridegroom', 'bridle', 'brief', 'brier', 'bright', 'brim', 'brimstone',
    'brink', 'broad', 'brood', 'brook', 'broom', 'broth', 'brother', 'brought',
    'brow', 'brown', 'bruise', 'brute', 'bud', 'buffet', 'build', 'built',
    'bull', 'bullock', 'bulwark', 'bunch', 'bundle', 'burden', 'burn', 'burst',
    'bury', 'bush', 'bushel', 'busy', 'but', 'butter', 'butterfly', 'buy',
    'buzzard', 'by',
    # C
    'cab', 'cabin', 'cage', 'cake', 'calf', 'calm', 'camel', 'camp', 'cane',
    'cap', 'cape', 'captive', 'captor', 'car', 'carcase', 'care', 'careful',
    'carpenter', 'carriage', 'carry', 'cart', 'carve', 'case', 'cask', 'cast',
    'castle', 'cat', 'catch', 'caterpillar', 'cattle', 'cause', 'cave',
    'cease', 'cedar', 'ceiling', 'cellar', 'center', 'chaff', 'chain', 'chair',
    'chalk', 'chamber', 'champion', 'chance', 'chant', 'chaos', 'charge',
    'chariot', 'charity', 'charm', 'chase', 'chaste', 'cheek', 'cheer',
    'cheese', 'cherry', 'chest', 'chestnut', 'chew', 'chief', 'child',
    'childhood', 'chill', 'chin', 'choice', 'choke', 'choose', 'chop',
    'chord', 'chorus', 'christ', 'church', 'churn', 'cinnamon', 'circle',
    'citizen', 'city', 'civil', 'claim', 'clamor', 'clap', 'clasp', 'class',
    'claw', 'clay', 'clean', 'cleanse', 'clear', 'cleave', 'cleft', 'clerk',
    'clever', 'cliff', 'climb', 'cling', 'cloak', 'clock', 'clod', 'close',
    'cloth', 'clothe', 'clothes', 'clothing', 'cloud', 'club', 'coal',
    'coast', 'coat', 'cock', 'coffin', 'coil', 'coin', 'cold', 'collar',
    'colony', 'color', 'colt', 'come', 'comely', 'comet', 'comfort', 'coming',
    'command', 'commit', 'common', 'companion', 'company', 'compel', 'complete',
    'conceal', 'conceit', 'conceive', 'concord', 'concubine', 'concupiscence',
    'condemn', 'conduct', 'confess', 'confine', 'confirm', 'confute', 'conjure',
    'conquer', 'consent', 'consort', 'constant', 'constrain', 'consult',
    'consume', 'contain', 'contemn', 'contempt', 'contend', 'content',
    'continue', 'contract', 'converse', 'convert', 'convey', 'convince',
    'cook', 'cool', 'copper', 'copy', 'cord', 'core', 'coriander', 'cork',
    'corn', 'corner', 'correct', 'corrupt', 'costly', 'cot', 'cottage',
    'cotton', 'couch', 'cough', 'council', 'counsel', 'count', 'counter',
    'country', 'couple', 'courage', 'course', 'court', 'cousin', 'covenant',
    'cover', 'covet', 'cow', 'coward', 'cowl', 'craft', 'crag', 'crane',
    'crash', 'crave', 'crawl', 'create', 'creep', 'crib', 'crime', 'cripple',
    'crook', 'crop', 'cross', 'crouch', 'crow', 'crowd', 'crown', 'crucify',
    'cruel', 'crumb', 'crush', 'cry', 'crystal', 'cubit', 'cuckoo', 'cumber',
    'cup', 'curd', 'cure', 'curl', 'curse', 'curtain', 'cushion', 'custody',
    'custom', 'cut', 'cymbal',
    # D
    'daily', 'dam', 'damage', 'damsel', 'dance', 'dandle', 'dark', 'darkness',
    'darling', 'dart', 'dash', 'daub', 'daughter', 'dawn', 'day', 'dayspring',
    'daytime', 'dazzle', 'dead', 'deaf', 'deal', 'dealings', 'dear', 'dearth',
    'death', 'debate', 'debt', 'decay', 'deceit', 'deceive', 'decide',
    'deck', 'declare', 'decline', 'decree', 'deed', 'deep', 'deeply', 'defeat',
    'defile', 'define', 'defraud', 'defy', 'degree', 'delay', 'delicate',
    'delight', 'deliver', 'demand', 'demon', 'den', 'denote', 'deny', 'depart',
    'depend', 'depict', 'deplore', 'deposit', 'deprive', 'depth', 'deputy',
    'desert', 'deserve', 'design', 'desire', 'desk', 'despair', 'despise',
    'despite', 'destiny', 'destitute', 'destroy', 'detest', 'devil', 'devious',
    'devise', 'devote', 'devour', 'devout', 'dew', 'dial', 'diamond', 'die',
    'different', 'dig', 'dignity', 'dim', 'dine', 'dip', 'direct', 'dirt',
    'dirty', 'disarm', 'discard', 'disciple', 'disclose', 'discord', 'disease',
    'disguise', 'dish', 'dismal', 'dismay', 'dismiss', 'dispatch', 'dispel',
    'dispense', 'display', 'dispose', 'dispute', 'dissent', 'ditch', 'divers',
    'divide', 'divine', 'do', 'dock', 'doctor', 'dog', 'doll', 'dome', 'done',
    'donkey', 'doom', 'door', 'dot', 'dote', 'double', 'doubt', 'dough',
    'dove', 'down', 'dowry', 'doze', 'dozen', 'drag', 'dragon', 'drain',
    'drake', 'drama', 'draw', 'drawer', 'dread', 'dream', 'dregs', 'drench',
    'dress', 'drift', 'drill', 'drink', 'drip', 'drive', 'driver', 'drop',
    'dross', 'drought', 'drown', 'drug', 'drum', 'drunk', 'dry', 'duck',
    'due', 'dull', 'dumb', 'dung', 'dungeon', 'during', 'dusk', 'dust', 'duty',
    'dwarf', 'dwell', 'dye',
    # E
    'each', 'eager', 'eagle', 'ear', 'early', 'earn', 'earnest', 'earth',
    'earthly', 'earthquake', 'ease', 'east', 'easterly', 'easy', 'eat', 'ebb',
    'ebony', 'echo', 'edge', 'edict', 'edify', 'edition', 'effort', 'egg',
    'eight', 'eighteen', 'eighth', 'either', 'elbow', 'elder', 'eldest',
    'elect', 'element', 'elephant', 'eleven', 'elf', 'elm', 'else', 'embark',
    'embassy', 'embezzle', 'emblem', 'embrace', 'emerald', 'eminent', 'empire',
    'employ', 'empty', 'end', 'endear', 'endow', 'endure', 'enemy', 'energy',
    'engage', 'engrave', 'enjoin', 'enjoy', 'enlarge', 'enlighten', 'enough',
    'enquire', 'enrich', 'enrol', 'ensign', 'ensue', 'ensure', 'enter',
    'entrance', 'entreat', 'entrust', 'envy', 'equal', 'equity', 'err',
    'errand', 'escape', 'essence', 'estate', 'esteem', 'estrange', 'eternal',
    'evade', 'eve', 'even', 'evening', 'event', 'ever', 'every', 'evidence',
    'evil', 'ewe', 'exact', 'exalt', 'except', 'exceed', 'excellent', 'excess',
    'exchange', 'excite', 'exclaim', 'exclude', 'excuse', 'exempt', 'exercise',
    'exhort', 'exile', 'exist', 'exit', 'expand', 'expect', 'expel', 'expend',
    'expert', 'expire', 'explain', 'explore', 'expose', 'express', 'extend',
    'extol', 'extreme', 'eye', 'eyelid',
    # F
    'fable', 'face', 'fade', 'fail', 'faint', 'fair', 'faith', 'fall',
    'fallow', 'false', 'fame', 'family', 'famine', 'famish', 'famous', 'fan',
    'fancy', 'fang', 'far', 'fare', 'farm', 'farther', 'fashion', 'fast',
    'fat', 'fate', 'father', 'fathom', 'favor', 'fawn', 'fear', 'feast',
    'feat', 'feather', 'fed', 'fee', 'feeble', 'feed', 'feel', 'feet',
    'fell', 'fellow', 'female', 'fen', 'fence', 'fern', 'ferry', 'fertile',
    'festival', 'fetch', 'fetter', 'feud', 'few', 'fickle', 'fiction', 'fie',
    'field', 'fierce', 'fiery', 'fifteen', 'fifty', 'fig', 'fight', 'figure',
    'file', 'fill', 'filth', 'fin', 'final', 'find', 'fine', 'finger', 'fir',
    'fire', 'firm', 'first', 'firstborn', 'firstling', 'fish', 'fist', 'fit',
    'five', 'fix', 'flag', 'flail', 'flame', 'flank', 'flap', 'flash', 'flat',
    'flatter', 'flax', 'flea', 'flee', 'fleece', 'fleet', 'flesh', 'flight',
    'fling', 'flint', 'flirt', 'float', 'flock', 'flood', 'floor', 'flour',
    'flow', 'flower', 'flute', 'fly', 'foam', 'fodder', 'foe', 'fog', 'foil',
    'fold', 'folk', 'follow', 'folly', 'food', 'fool', 'foolish', 'foot',
    'for', 'forbid', 'force', 'ford', 'fore', 'forecast', 'forehead', 'foreign',
    'forest', 'foretell', 'forever', 'forfeit', 'forget', 'forgive', 'fork',
    'form', 'fornication', 'forsake', 'fort', 'forth', 'fortune', 'forty',
    'forward', 'foul', 'found', 'four', 'fourteen', 'fourth', 'fowl', 'fowler',
    'fox', 'fragment', 'frail', 'frame', 'fraud', 'free', 'freely', 'fresh',
    'freshness', 'fret', 'friend', 'fright', 'fringe', 'frivolous', 'fro',
    'frog', 'from', 'front', 'frost', 'froward', 'frown', 'frugal', 'fruit',
    'fry', 'fuel', 'fugitive', 'fulfil', 'full', 'fuller', 'fun', 'fund',
    'funeral', 'fur', 'furious', 'furlong', 'furnace', 'furrow', 'further',
    'fury', 'future',
    # Continuing with common ones...
    'gad', 'gain', 'gait', 'gall', 'gallery', 'galley', 'gallows', 'game',
    'garden', 'garlic', 'garment', 'garrison', 'gate', 'gather', 'gaze', 'gear',
    'general', 'generation', 'gentle', 'gentleman', 'genuine', 'get', 'ghost',
    'giant', 'gift', 'gird', 'girdle', 'girl', 'give', 'glad', 'glade', 'gland',
    'glass', 'glean', 'glee', 'glide', 'glimmer', 'glitter', 'gloom', 'glorify',
    'glorious', 'glory', 'glove', 'glow', 'glue', 'glut', 'glutton', 'gnash',
    'gnat', 'gnaw', 'go', 'goad', 'goal', 'goat', 'god', 'godly', 'gold',
    'golden', 'gone', 'good', 'goods', 'goose', 'gore', 'gorge', 'gospel',
    'gourd', 'govern', 'gown', 'grace', 'graft', 'grain', 'granary', 'grand',
    'granddaughter', 'grandfather', 'grandmother', 'grandson', 'grant', 'grape',
    'grapple', 'grasp', 'grass', 'grasshopper', 'grate', 'grave', 'gravel',
    'gray', 'graze', 'great', 'greed', 'green', 'greet', 'grey', 'grief',
    'grievous', 'grin', 'grind', 'grisled', 'groan', 'groin', 'gross', 'ground',
    'group', 'grove', 'grow', 'grown', 'growth', 'grudge', 'grunt', 'guarantee',
    'guard', 'guess', 'guest', 'guide', 'guild', 'guile', 'guilt', 'guilty',
    'gulf', 'gulp', 'gum', 'gun', 'gush', 'gust',
    # H I J K L M N O P Q R S T U V W X Y Z
    'habit', 'hack', 'hail', 'hair', 'hairy', 'half', 'hall', 'hallow',
    'halt', 'ham', 'hammer', 'hand', 'handful', 'handicraft', 'handkerchief',
    'handle', 'handwriting', 'hang', 'happen', 'happy', 'harbor', 'hard',
    'hare', 'harlot', 'harm', 'harmless', 'harp', 'harrow', 'harsh', 'hart',
    'harvest', 'haste', 'hat', 'hatch', 'hate', 'hateful', 'hatred', 'have',
    'haven', 'hawk', 'hay', 'haze', 'he', 'head', 'heal', 'health', 'heap',
    'hear', 'heard', 'heart', 'hearken', 'hearth', 'hearty', 'heat', 'heath',
    'heathen', 'heave', 'heaven', 'heavenly', 'heavy', 'heel', 'height', 'heir',
    'hell', 'helmet', 'help', 'hemlock', 'hen', 'hence', 'her', 'herald',
    'herb', 'herd', 'herdsman', 'here', 'hereafter', 'heritage', 'hermit',
    'hero', 'herself', 'hesitate', 'hew', 'hidden', 'hide', 'high', 'highway',
    'hill', 'him', 'himself', 'hind', 'hinge', 'hint', 'hip', 'hire', 'hireling',
    'his', 'hiss', 'history', 'hit', 'hither', 'hive', 'hoar', 'hoary', 'hog',
    'hold', 'hole', 'holiday', 'holiness', 'hollow', 'holy', 'home', 'homely',
    'honest', 'honey', 'honor', 'hoof', 'hook', 'hope', 'horizon', 'horn',
    'hornet', 'horrible', 'horror', 'horse', 'horseman', 'hospitable',
    'hospitality', 'host', 'hostage', 'hostile', 'hot', 'hour', 'house',
    'household', 'housewife', 'how', 'hug', 'huge', 'hull', 'hum', 'humane',
    'humble', 'humility', 'humor', 'hundred', 'hung', 'hungry', 'hunt', 'hurl',
    'hurt', 'husband', 'hut', 'hymn', 'hypocrisy', 'hypocrite', 'hyssop',
    'ice', 'idea', 'ideal', 'idle', 'idol', 'if', 'ignorant', 'ill', 'image',
    'imagine', 'imitate', 'immediate', 'immodest', 'immortal', 'impart', 'impel',
    'imperial', 'implement', 'imply', 'import', 'important', 'impose', 'impress',
    'improve', 'impudent', 'impure', 'in', 'inasmuch', 'incense', 'inch',
    'incline', 'include', 'income', 'increase', 'incur', 'indeed', 'indoor',
    'indulge', 'infant', 'infect', 'infer', 'infinite', 'inflame', 'inflict',
    'inform', 'inhabit', 'inherit', 'initial', 'injure', 'injustice', 'ink',
    'inkhorn', 'inland', 'inn', 'inner', 'innocent', 'inquire', 'inscribe',
    'insect', 'inside', 'insist', 'inspire', 'instant', 'instead', 'instruct',
    'insult', 'intend', 'intent', 'interest', 'into', 'intrude', 'invite',
    'inward', 'iron', 'is', 'island', 'isle', 'issue', 'it', 'itch', 'item',
    'its', 'itself', 'ivory', 'ivy', 'jasper', 'jaw', 'jealous', 'jealousy',
    'jerk', 'jest', 'jewel', 'job', 'join', 'joint', 'journey', 'joy', 'joyful',
    'judge', 'juice', 'jump', 'just', 'justice', 'justify', 'keel', 'keen',
    'keep', 'keeper', 'kennel', 'kernel', 'kettle', 'key', 'kick', 'kid',
    'kidney', 'kill', 'kin', 'kind', 'king', 'kingdom', 'kinsman', 'kiss',
    'kitchen', 'kite', 'knead', 'knee', 'kneel', 'knife', 'knight', 'knit',
    'knob', 'knock', 'knot', 'know', 'knowledge', 'known', 'kohl', 'labor',
    'lace', 'lack', 'lad', 'ladder', 'lade', 'lady', 'laid', 'lain', 'lair',
    'lake', 'lamb', 'lame', 'lament', 'lamp', 'lance', 'land', 'lane', 'language',
    'languish', 'lantern', 'lap', 'large', 'lark', 'last', 'late', 'latter',
    'laugh', 'laundry', 'lavish', 'law', 'lay', 'lazy', 'lead', 'leader',
    'leaf', 'league', 'lean', 'leap', 'learn', 'least', 'leather', 'leave',
    'leaven', 'leech', 'left', 'leg', 'legal', 'lend', 'length', 'lentil',
    'leopard', 'leper', 'leprosy', 'less', 'lesson', 'lest', 'let', 'lethal',
    'letter', 'lettuce', 'level', 'lewd', 'liar', 'libel', 'liberty', 'library',
    'lid', 'lie', 'life', 'lift', 'light', 'lightning', 'like', 'liken', 'lily',
    'limb', 'lime', 'limp', 'line', 'linger', 'linen', 'lintel', 'lion', 'lip',
    'lisp', 'list', 'listen', 'little', 'live', 'liver', 'living', 'lizard',
    'load', 'loaf', 'loan', 'loathe', 'lock', 'locust', 'lodge', 'lofty', 'log',
    'loin', 'lonely', 'long', 'look', 'loose', 'loot', 'lord', 'lose', 'loss',
    'lost', 'lot', 'loud', 'love', 'lovely', 'low', 'loyalty', 'lull', 'lunatic',
    'lunch', 'lung', 'lurk', 'lust', 'luxury', 'lyre',
    'mad', 'madam', 'made', 'mail', 'main', 'maintain', 'majesty', 'make',
    'male', 'malice', 'mammal', 'man', 'mane', 'mangle', 'mankind', 'manna',
    'manner', 'mantle', 'manure', 'many', 'map', 'marble', 'march', 'margin',
    'marine', 'mark', 'market', 'marriage', 'marrow', 'marry', 'marsh',
    'marshal', 'martyr', 'marvel', 'mash', 'mask', 'mass', 'mast', 'master',
    'mastery', 'mat', 'match', 'mate', 'maul', 'may', 'maze', 'me', 'meadow',
    'meal', 'mean', 'means', 'meantime', 'meanwhile', 'measure', 'meat', 'meet',
    'melon', 'melt', 'men', 'mend', 'merchant', 'mercy', 'mere', 'merit',
    'merry', 'mesh', 'mess', 'messenger', 'metal', 'mete', 'mice', 'midday',
    'middle', 'midnight', 'midst', 'midwife', 'might', 'mild', 'mildew', 'mile',
    'milk', 'mill', 'millet', 'million', 'mind', 'mine', 'mingle', 'minnow',
    'mint', 'minute', 'miracle', 'mirror', 'mirth', 'mischief', 'misfortune',
    'miss', 'mist', 'mistake', 'mistress', 'mite', 'mix', 'moan', 'moat',
    'mob', 'mock', 'mode', 'model', 'moderate', 'modest', 'moist', 'mole',
    'molest', 'molten', 'moment', 'money', 'month', 'mood', 'moon', 'more',
    'moreover', 'morn', 'morsel', 'mortal', 'mortar', 'most', 'moth', 'mother',
    'motor', 'mouldy', 'mount', 'mountain', 'mourn', 'mouse', 'moustache',
    'mouth', 'move', 'much', 'mud', 'mule', 'multiply', 'multitude', 'mummy',
    'murder', 'murmur', 'muscle', 'music', 'musician', 'must', 'mustard',
    'mute', 'mutton', 'my', 'myrrh', 'myrtle', 'myself', 'mystery',
    'nail', 'name', 'nap', 'narrow', 'nasty', 'nation', 'native', 'nature',
    'naught', 'navy', 'nay', 'near', 'neat', 'necessary', 'neck', 'need',
    'needle', 'needy', 'neglect', 'neigh', 'neighbor', 'neither', 'nephew',
    'nerve', 'nest', 'net', 'nether', 'nettle', 'never', 'new', 'next', 'nice',
    'nigh', 'night', 'nightly', 'nine', 'nineteen', 'ninety', 'nip', 'no',
    'noble', 'nod', 'noise', 'none', 'noon', 'nor', 'north', 'nose', 'nostril',
    'not', 'note', 'nothing', 'notice', 'nourish', 'novel', 'now', 'nude',
    'nugget', 'null', 'number', 'numerous', 'nurse', 'nursery', 'nut',
    'nymph',
    'oak', 'oar', 'oath', 'obey', 'obese', 'oblige', 'obscure', 'observe',
    'obstruct', 'obtain', 'occasion', 'ocean', 'odd', 'odious', 'odor', 'off',
    'offal', 'offend', 'offer', 'office', 'officer', 'often', 'ogre', 'oil',
    'ointment', 'old', 'olive', 'omen', 'on', 'once', 'one', 'onion', 'only',
    'onward', 'onyx', 'ooze', 'opal', 'open', 'oppose', 'oppress', 'or',
    'oracle', 'orb', 'orchard', 'orchid', 'order', 'organ', 'orient', 'origin',
    'ornament', 'orphan', 'other', 'otherwise', 'ouch', 'ought', 'our',
    'ourselves', 'out', 'outcast', 'outer', 'outlaw', 'oven', 'over', 'overcome',
    'overflow', 'overhead', 'overhear', 'overlap', 'overlay', 'overlook',
    'overthrow', 'overturn', 'owe', 'owl', 'own', 'ox', 'oxen',
    'pace', 'pack', 'pad', 'paddle', 'page', 'pail', 'pain', 'paint', 'pair',
    'palace', 'pale', 'palm', 'palsy', 'pan', 'pane', 'pang', 'pant', 'paper',
    'par', 'parable', 'paradise', 'parallel', 'parch', 'pardon', 'parent',
    'park', 'parlor', 'parrot', 'parse', 'part', 'partake', 'partial', 'party',
    'pass', 'passage', 'past', 'paste', 'pasture', 'pat', 'patch', 'path',
    'patient', 'patrol', 'patron', 'pattern', 'pause', 'pave', 'paw', 'pay',
    'pea', 'peace', 'peach', 'peacock', 'peak', 'pear', 'pearl', 'pebble',
    'peck', 'pedal', 'peek', 'peel', 'peep', 'peer', 'peg', 'pelican', 'pelt',
    'pen', 'pence', 'pencil', 'penny', 'pension', 'people', 'pepper', 'perch',
    'perfect', 'perform', 'perfume', 'perhaps', 'peril', 'period', 'perish',
    'permanent', 'permit', 'perpetual', 'perplex', 'persist', 'person', 'perturb',
    'pet', 'pewter', 'phantom', 'phase', 'phrase', 'physic', 'pick', 'picture',
    'piece', 'pier', 'pierce', 'piety', 'pig', 'pigeon', 'pike', 'pile',
    'pilgrim', 'pillar', 'pillow', 'pilot', 'pin', 'pinch', 'pine', 'pink',
    'pint', 'pious', 'pipe', 'pirate', 'pit', 'pitch', 'pitcher', 'pith',
    'pity', 'place', 'plague', 'plain', 'plait', 'plan', 'plane', 'plank',
    'plant', 'plaster', 'plate', 'play', 'plead', 'pleasant', 'please',
    'pleasure', 'pledge', 'plenty', 'plot', 'plough', 'plow', 'plug', 'plum',
    'plumage', 'plumb', 'plume', 'plump', 'plunder', 'plunge', 'pocket', 'poem',
    'poet', 'poetry', 'point', 'poise', 'poison', 'pole', 'polish', 'polite',
    'poll', 'pomegranate', 'pond', 'pony', 'pool', 'poor', 'poplar', 'poppy',
    'popular', 'populous', 'porch', 'porridge', 'port', 'portal', 'porter',
    'portion', 'post', 'pot', 'potato', 'potter', 'pouch', 'poultry', 'pound',
    'pour', 'pout', 'poverty', 'powder', 'power', 'praise', 'prance', 'pray',
    'prayer', 'preach', 'precede', 'precious', 'precise', 'predict', 'prefer',
    'present', 'preserve', 'press', 'pretence', 'pretend', 'pretty', 'prevail',
    'prevent', 'prey', 'price', 'prick', 'pride', 'priest', 'prim', 'prime',
    'prince', 'principal', 'print', 'prior', 'prism', 'prison', 'private',
    'privy', 'prize', 'probably', 'prod', 'produce', 'profane', 'profit',
    'profuse', 'prolong', 'prompt', 'prone', 'prong', 'proof', 'prop', 'proper',
    'prophet', 'prosper', 'protect', 'protest', 'proud', 'prove', 'proverb',
    'provide', 'prowl', 'prude', 'prudent', 'prune', 'pry', 'psalm', 'public',
    'publish', 'puff', 'puke', 'pull', 'pulse', 'pump', 'punish', 'pup',
    'pupil', 'puppet', 'puppy', 'pure', 'purge', 'purify', 'purity', 'purloin',
    'purple', 'purpose', 'purse', 'pursue', 'push', 'put', 'putrid', 'pygmy',
    'quack', 'quail', 'quake', 'qualify', 'quality', 'quantity', 'quarrel',
    'quart', 'quarter', 'quartz', 'queen', 'queer', 'quench', 'question',
    'queue', 'quick', 'quiet', 'quill', 'quilt', 'quip', 'quit', 'quite',
    'quiver', 'quoit', 'quote',
    'rabbi', 'rabbit', 'race', 'rack', 'radiant', 'radish', 'rag', 'rage',
    'raid', 'rail', 'raiment', 'rain', 'rainbow', 'raise', 'raisin', 'rake',
    'ram', 'ramble', 'rampart', 'ran', 'random', 'range', 'rank', 'ransack',
    'ransom', 'rapid', 'rare', 'rascal', 'rash', 'rat', 'rate', 'rattle',
    'ravage', 'rave', 'raven', 'ravenous', 'raw', 'ray', 'razor', 'reach',
    'read', 'ready', 'real', 'reap', 'rear', 'reason', 'rebel', 'rebuke',
    'recall', 'receive', 'recent', 'recess', 'recite', 'reckon', 'recline',
    'recluse', 'recoil', 'recollect', 'recommend', 'record', 'recount',
    'recover', 'red', 'reed', 'reef', 'reek', 'reel', 'refer', 'refine',
    'reflect', 'reform', 'refrain', 'refresh', 'refuge', 'refund', 'refuse',
    'regain', 'regard', 'reign', 'rein', 'reject', 'rejoice', 'relate', 'release',
    'relent', 'relief', 'relieve', 'rely', 'remain', 'remedy', 'remember',
    'remind', 'remiss', 'remnant', 'remorse', 'remote', 'remove', 'rend',
    'render', 'renew', 'renown', 'rent', 'repair', 'repast', 'repeat', 'repel',
    'repent', 'reply', 'report', 'repose', 'reprove', 'request', 'require',
    'rescue', 'resemble', 'reserve', 'reside', 'resign', 'resist', 'respect',
    'rest', 'restless', 'restore', 'restrain', 'result', 'retail', 'retain',
    'retire', 'retreat', 'return', 'reveal', 'revel', 'revenge', 'revere',
    'reverse', 'revile', 'revise', 'revive', 'revoke', 'revolt', 'reward',
    'rhyme', 'rib', 'ribbon', 'rice', 'rich', 'riches', 'rid', 'riddle',
    'ride', 'ridge', 'right', 'righteous', 'rigid', 'rim', 'rind', 'ring',
    'riot', 'rip', 'ripe', 'ripen', 'ripple', 'rise', 'risk', 'rite', 'rival',
    'river', 'road', 'roam', 'roar', 'roast', 'rob', 'robe', 'robin', 'rock',
    'rod', 'rogue', 'roll', 'roof', 'rook', 'room', 'roost', 'root', 'rope',
    'rose', 'rot', 'rough', 'round', 'rouse', 'rove', 'row', 'royal', 'rub',
    'rubbish', 'ruby', 'rude', 'ruffian', 'rug', 'rugged', 'ruin', 'rule',
    'rumble', 'rumor', 'rump', 'run', 'rush', 'rust', 'rustle',
    'sable', 'sack', 'sacred', 'sad', 'saddle', 'safe', 'sag', 'sage', 'said',
    'sail', 'sailor', 'saint', 'sake', 'salary', 'sale', 'salt', 'salute',
    'same', 'sand', 'sane', 'sap', 'sash', 'satisfy', 'save', 'saw', 'say',
    'scab', 'scaffold', 'scald', 'scale', 'scalp', 'scamper', 'scan', 'scant',
    'scar', 'scarce', 'scare', 'scarf', 'scarlet', 'scatter', 'scent', 'scheme',
    'scholar', 'school', 'scold', 'scorn', 'scorpion', 'scout', 'scowl',
    'scrap', 'scrape', 'scratch', 'scream', 'screen', 'screw', 'scribe',
    'script', 'scroll', 'scrub', 'scurvy', 'sea', 'seal', 'seam', 'search',
    'season', 'seat', 'second', 'secret', 'sect', 'see', 'seed', 'seek',
    'seem', 'seen', 'seethe', 'seize', 'seldom', 'select', 'self', 'sell',
    'send', 'sense', 'sent', 'sentinel', 'sentry', 'separate', 'serpent',
    'servant', 'serve', 'set', 'settle', 'seven', 'seventy', 'several',
    'severe', 'sew', 'sex', 'shabby', 'shade', 'shadow', 'shaft', 'shake',
    'shall', 'shallow', 'sham', 'shame', 'shape', 'share', 'shark', 'sharp',
    'sharpen', 'shave', 'shawl', 'she', 'sheaf', 'shear', 'sheath', 'shed',
    'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shelter', 'shepherd',
    'sheriff', 'shew', 'shield', 'shift', 'shine', 'shingle', 'ship', 'shirt',
    'shiver', 'shock', 'shoe', 'shoot', 'shop', 'shore', 'short', 'should',
    'shoulder', 'shout', 'shove', 'show', 'shred', 'shrewd', 'shriek', 'shrill',
    'shrink', 'shroud', 'shrub', 'shrug', 'shudder', 'shuffle', 'shun', 'shut',
    'sick', 'sickle', 'side', 'siege', 'sift', 'sigh', 'sight', 'sign',
    'signal', 'silent', 'silk', 'silly', 'silver', 'simple', 'sin', 'since',
    'sinew', 'sing', 'single', 'sink', 'sip', 'sir', 'sit', 'six', 'sixty',
    'size', 'skate', 'skeleton', 'sketch', 'ski', 'skiff', 'skill', 'skim',
    'skin', 'skip', 'skirt', 'skulk', 'skull', 'sky', 'slab', 'slack', 'slain',
    'slam', 'slander', 'slap', 'slash', 'slate', 'slaughter', 'slave', 'slay',
    'sled', 'sleep', 'sleet', 'sleeve', 'slice', 'slide', 'slight', 'slim',
    'slime', 'sling', 'slink', 'slip', 'slit', 'slope', 'sloth', 'slough',
    'slow', 'sludge', 'slum', 'slumber', 'sly', 'small', 'smart', 'smear',
    'smell', 'smile', 'smite', 'smith', 'smoke', 'smooth', 'snail', 'snake',
    'snap', 'snare', 'snarl', 'snatch', 'sneer', 'sneeze', 'sniff', 'snore',
    'snort', 'snout', 'snow', 'snub', 'snuff', 'so', 'soak', 'soap', 'soar',
    'sob', 'sober', 'sod', 'soft', 'soften', 'soil', 'solace', 'solder',
    'soldier', 'sole', 'solemn', 'solid', 'solve', 'some', 'somebody', 'someone',
    'something', 'sometime', 'somewhat', 'son', 'song', 'soon', 'soot',
    'soothe', 'sop', 'sore', 'sorrow', 'sorry', 'sort', 'soul', 'sound',
    'sour', 'source', 'south', 'sow', 'space', 'spade', 'span', 'spare',
    'spark', 'sparrow', 'speak', 'spear', 'speech', 'speed', 'spell', 'spelt',
    'spend', 'sphere', 'spice', 'spider', 'spike', 'spill', 'spin', 'spine',
    'spire', 'spirit', 'spit', 'spite', 'splash', 'splendid', 'split', 'spoil',
    'sponge', 'spoon', 'sport', 'spot', 'spout', 'sprain', 'sprawl', 'spray',
    'spread', 'spring', 'sprinkle', 'spume', 'spur', 'spy', 'squad', 'square',
    'squash', 'squat', 'squeal', 'squeeze', 'squint', 'stab', 'stable', 'stack',
    'staff', 'stag', 'stage', 'stagger', 'stain', 'stair', 'stake', 'stalk',
    'stall', 'stammer', 'stamp', 'stand', 'staple', 'star', 'starch', 'stare',
    'start', 'startle', 'starve', 'state', 'statue', 'stature', 'statute',
    'staunch', 'stay', 'stead', 'steady', 'steal', 'stealth', 'steam', 'steed',
    'steel', 'steep', 'steer', 'stem', 'step', 'stern', 'stew', 'stick',
    'stiff', 'stifle', 'still', 'sting', 'stink', 'stint', 'stir', 'stitch',
    'stock', 'stomach', 'stone', 'stool', 'stoop', 'stop', 'store', 'storehouse',
    'stork', 'storm', 'story', 'stout', 'stove', 'straggle', 'straight',
    'strain', 'strait', 'strand', 'strange', 'stranger', 'strap', 'straw',
    'stray', 'streak', 'stream', 'street', 'strength', 'stress', 'stretch',
    'strict', 'stride', 'strife', 'strike', 'string', 'strip', 'stripe',
    'strive', 'stroke', 'stroll', 'strong', 'stronghold', 'struggle', 'stud',
    'study', 'stuff', 'stumble', 'stun', 'stung', 'stupid', 'sturdy', 'stutter',
    'style', 'subdue', 'subject', 'submit', 'subtle', 'succeed', 'such',
    'suck', 'suckle', 'sudden', 'suffer', 'suffice', 'sugar', 'suggest',
    'suit', 'sulk', 'sullen', 'sum', 'summer', 'summon', 'sun', 'sunder',
    'sundry', 'sung', 'sunlight', 'sunny', 'sunset', 'sup', 'superb', 'supper',
    'supply', 'support', 'suppose', 'sure', 'surf', 'surly', 'surpass',
    'surplus', 'surprise', 'surround', 'survey', 'survive', 'suspend', 'swab',
    'swag', 'swain', 'swallow', 'swam', 'swamp', 'swan', 'swap', 'swarm',
    'sway', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swelter', 'swerve',
    'swift', 'swim', 'swindle', 'swine', 'swing', 'switch', 'swivel', 'swoon',
    'swoop', 'sword', 'sworn', 'swum', 'swung', 'symbol', 'sympathy', 'system',
    'table', 'tablet', 'tack', 'tackle', 'tact', 'tad', 'tag', 'tail', 'tailor',
    'take', 'tale', 'talk', 'tall', 'talon', 'tame', 'tang', 'tank', 'tap',
    'tape', 'tar', 'tardy', 'target', 'tarry', 'task', 'tassel', 'taste',
    'tatter', 'taunt', 'tavern', 'tax', 'taxes', 'tea', 'teach', 'team',
    'tear', 'teat', 'tedious', 'teem', 'teeth', 'tell', 'temple', 'ten',
    'tend', 'tender', 'tent', 'tenth', 'terrible', 'terror', 'test', 'testify',
    'tether', 'text', 'than', 'thank', 'that', 'thatch', 'the', 'their',
    'them', 'themselves', 'then', 'there', 'these', 'they', 'thick', 'thicket',
    'thief', 'thigh', 'thimble', 'thin', 'thine', 'thing', 'think', 'third',
    'thirst', 'thirteen', 'thirty', 'this', 'thistle', 'thither', 'thong',
    'thorn', 'those', 'thou', 'though', 'thought', 'thousand', 'thread',
    'threat', 'three', 'thresh', 'threshold', 'threw', 'thrice', 'thrill',
    'throat', 'throng', 'throne', 'through', 'throw', 'thrush', 'thrust',
    'thumb', 'thunder', 'thus', 'thy', 'tickle', 'tide', 'tidings', 'tidy',
    'tie', 'tiger', 'tight', 'tile', 'till', 'tilt', 'timber', 'time', 'timid',
    'tin', 'tinder', 'tingle', 'tiny', 'tip', 'tire', 'tired', 'tithe', 'title',
    'to', 'toad', 'toast', 'today', 'toe', 'together', 'toil', 'token',
    'told', 'toll', 'tomb', 'tomorrow', 'tone', 'tongue', 'tonight', 'too',
    'took', 'tool', 'tooth', 'top', 'topaz', 'topic', 'torch', 'tore', 'torn',
    'torrent', 'torture', 'toss', 'total', 'touch', 'tough', 'tour', 'toward',
    'towel', 'tower', 'town', 'toy', 'trace', 'track', 'trade', 'traffic',
    'trail', 'train', 'traitor', 'tramp', 'trance', 'trap', 'trash', 'travel',
    'travail', 'tread', 'treason', 'treasure', 'treat', 'tree', 'trek',
    'tremble', 'trench', 'trial', 'tribe', 'trick', 'trim', 'trio', 'trip',
    'triumph', 'trip', 'troop', 'trot', 'trouble', 'trough', 'troupe', 'trout',
    'truce', 'truck', 'true', 'trumpet', 'trunk', 'trust', 'truth', 'try',
    'tub', 'tube', 'tuck', 'tuft', 'tug', 'tumble', 'tumult', 'tune', 'turf',
    'turn', 'turtle', 'tusk', 'tutor', 'twain', 'twang', 'tweak', 'twelve',
    'twenty', 'twice', 'twig', 'twilight', 'twin', 'twine', 'twinge', 'twinkle',
    'twirl', 'twist', 'twit', 'twitch', 'two', 'type', 'tyrant',
    'udder', 'ugly', 'umbrella', 'unable', 'unaware', 'uncle', 'under',
    'understand', 'undertake', 'undo', 'undone', 'unequal', 'uneven', 'unfair',
    'unfold', 'unfurl', 'unhappy', 'unholy', 'uniform', 'union', 'unique',
    'unit', 'unite', 'universe', 'unjust', 'unkind', 'unknown', 'unless',
    'unlike', 'unload', 'unlock', 'unlucky', 'unmask', 'unpack', 'unpaid',
    'unplug', 'unreal', 'unrest', 'unripe', 'unroll', 'unseen', 'unsound',
    'until', 'unto', 'untold', 'untrue', 'unused', 'unwilling', 'unwise',
    'up', 'uphold', 'upkeep', 'upland', 'upon', 'upper', 'upright', 'uproar',
    'upset', 'upward', 'urchin', 'urge', 'urgent', 'us', 'use', 'useful',
    'useless', 'usher', 'usual', 'utmost', 'utter', 'uttermost',
    'vacate', 'vague', 'vain', 'vale', 'valiant', 'valid', 'valley', 'value',
    'valve', 'van', 'vane', 'vanish', 'vanity', 'vapor', 'variety', 'various',
    'varnish', 'vary', 'vase', 'vast', 'vault', 'veal', 'veer', 'veil', 'vein',
    'velvet', 'vendor', 'veneer', 'vent', 'verb', 'verdict', 'verify', 'verse',
    'very', 'vessel', 'vest', 'vex', 'vicar', 'vice', 'victim', 'victor',
    'victory', 'vie', 'view', 'vigil', 'vigor', 'vile', 'villa', 'village',
    'villain', 'vine', 'vinegar', 'vineyard', 'viol', 'violent', 'violet',
    'virgin', 'virtue', 'visage', 'visible', 'visit', 'visitor', 'visor',
    'vital', 'vivid', 'vixen', 'voice', 'void', 'volley', 'volume', 'voluntary',
    'vomit', 'vote', 'vouch', 'vow', 'voyage', 'vulgar', 'vulture',
    'wade', 'wafer', 'waft', 'wag', 'wage', 'wagon', 'waif', 'wail', 'waist',
    'wait', 'waiter', 'wake', 'walk', 'wall', 'wallet', 'wallow', 'wand',
    'wander', 'wane', 'want', 'war', 'warble', 'ward', 'wardrobe', 'ware',
    'warm', 'warn', 'warp', 'warrant', 'warrior', 'wart', 'wary', 'was',
    'wash', 'wasp', 'waste', 'watch', 'watchman', 'water', 'wave', 'waver',
    'wax', 'way', 'wayside', 'we', 'weak', 'weal', 'wealth', 'wean', 'weapon',
    'wear', 'weary', 'weasel', 'weather', 'weave', 'web', 'wed', 'wedge',
    'wedlock', 'weed', 'week', 'weep', 'weigh', 'weight', 'weird', 'welcome',
    'weld', 'welfare', 'well', 'welt', 'went', 'were', 'west', 'wet', 'whack',
    'whale', 'wharf', 'what', 'whatever', 'wheat', 'wheel', 'whelp', 'when',
    'whenever', 'where', 'whereas', 'wherever', 'wherewith', 'whet', 'whether',
    'which', 'while', 'whim', 'whimper', 'whine', 'whip', 'whirl', 'whirlpool',
    'whirlwind', 'whisker', 'whisper', 'whistle', 'whit', 'white', 'whither',
    'who', 'whoever', 'whole', 'whom', 'whop', 'whore', 'whose', 'why',
    'wick', 'wicked', 'wide', 'widow', 'wield', 'wife', 'wild', 'wilderness',
    'wile', 'will', 'willing', 'willow', 'wilt', 'win', 'wince', 'wind',
    'window', 'wine', 'wing', 'wink', 'winnow', 'winsome', 'wipe', 'wire',
    'wisdom', 'wise', 'wish', 'wisp', 'wit', 'witch', 'with', 'withal',
    'withdraw', 'wither', 'withhold', 'within', 'without', 'withstand',
    'witness', 'witty', 'woe', 'wolf', 'woman', 'womb', 'won', 'wonder',
    'wont', 'woo', 'wood', 'wool', 'word', 'wore', 'work', 'world', 'worm',
    'worn', 'worry', 'worse', 'worship', 'worst', 'worth', 'worthy', 'would',
    'wound', 'woven', 'wrap', 'wrath', 'wreak', 'wreath', 'wreck', 'wrench',
    'wrest', 'wrestle', 'wretch', 'wring', 'wrinkle', 'wrist', 'write', 'writ',
    'wrong', 'wrote', 'wroth', 'wrought', 'wrung', 'wry',
    'yam', 'yard', 'yarn', 'yawn', 'yea', 'year', 'yearly', 'yearn', 'yeast',
    'yell', 'yellow', 'yelp', 'yeoman', 'yes', 'yesterday', 'yet', 'yew',
    'yield', 'yoke', 'yolk', 'yon', 'yonder', 'you', 'young', 'your', 'yours',
    'yourself', 'youth',
    'zeal', 'zenith', 'zephyr', 'zero', 'zest', 'zone',
}

# Français safe (déjà correct)
FRENCH_SAFE = {
    'aigle', 'aile', 'air', 'arbre', 'argent', 'armé', 'autel', 'autre',
    'bois', 'bras', 'cahier', 'cause', 'cent', 'ciel', 'cinq', 'dieu',
    'douze', 'droit', 'eau', 'écho', 'élu', 'enfant', 'est', 'est',
    'excellent', 'feu', 'fin', 'fleur', 'fleuve', 'fois', 'fou', 'frère',
    'froid', 'fruit', 'guide', 'hier', 'idéal', 'image', 'immortel',
    'information', 'inspecteur', 'intervalle', 'jeune', 'joie', 'juge',
    'juif', 'juste', 'justice', 'lampe', 'langue', 'ligne', 'loi', 'long',
    'lune', 'maire', 'mal', 'malade', 'matin', 'mer', 'mère', 'midi',
    'mille', 'monde', 'monstre', 'mort', 'mot', 'motion', 'mouton', 'mur',
    'musique', 'muscle', 'neuf', 'nez', 'noir', 'nom', 'nord', 'nu',
    'oeil', 'oiseau', 'ombre', 'or', 'ordre', 'os', 'ouest', 'oui',
    'ours', 'paix', 'pas', 'passé', 'père', 'pied', 'pierre', 'place',
    'plaire', 'plat', 'plein', 'plume', 'poids', 'poil', 'port', 'pot',
    'poule', 'pouvoir', 'premier', 'prendre', 'prix', 'pur', 'quelle',
    'radieux', 'rade', 'raide', 'rare', 'rat', 'regarder', 'rêver', 'rire',
    'robe', 'roc', 'roi', 'rôle', 'rond', 'route', 'rouge', 'rose',
    'sage', 'sain', 'saint', 'salle', 'salon', 'sang', 'saut', 'science',
    'second', 'seigneur', 'sel', 'semaine', 'sept', 'service', 'seul',
    'six', 'sol', 'soleil', 'somme', 'son', 'sort', 'sourd', 'stable',
    'style', 'succès', 'sud', 'système', 'taire', 'tard', 'taxi', 'terre',
    'tête', 'thé', 'tibia', 'tige', 'tirer', 'titre', 'toile', 'toit',
    'tomate', 'tour', 'train', 'travail', 'très', 'trois', 'trop', 'trouble',
    'trouver', 'tuer', 'type', 'vache', 'vase', 'venir', 'vent', 'verbe',
    'verbe', 'vert', 'vide', 'vie', 'vierge', 'villa', 'village', 'ville',
    'vin', 'violence', 'violent', 'visage', 'visite', 'visiteur', 'vite',
    'voir', 'voisin', 'voix', 'vol', 'voler', 'voleur', 'vote', 'vrai',
    'vue', 'yeux',
}

# Words already processed in C4/C8 (will be detected since they're already translated)
# We don't need to track them explicitly — just skip where label_fr != mot


def main():
    print('Loading...')
    chunks_by_entry = {}
    for fp in sorted((DICT_DIR / 'isbe').glob('isbe-?.json')):
        with open(fp, encoding='utf-8-sig') as f:
            for e in json.load(f):
                chunks_by_entry[e['id']] = (e, fp.name)

    with open(DICT_DIR / 'concepts.json', encoding='utf-8') as f:
        concepts = json.load(f)

    suspects = []
    for c in concepts:
        label = c.get('label', '')
        cid = c['concept_id']
        if not label or c.get('category') != 'non_classifie':
            continue
        if re.search(r'[\s;,\-]', label):
            continue  # multi-word
        if re.search(r'[éèàçôûêâïëÉÈÀÇÔÛÊÂÏË]', label):
            continue  # has FR accents
        mot_lower = label.lower()
        if mot_lower not in ENGLISH_COMMON_NOUNS:
            continue  # not in our wordlist
        if mot_lower in FRENCH_SAFE:
            continue

        isbe_refs = [e for e in c.get('entries', []) if e.get('dictionary') == 'isbe']
        if not isbe_refs:
            continue
        primary = next((e for e in isbe_refs if e.get('is_primary_for_role')), isbe_refs[0])
        entry_info = chunks_by_entry.get(primary['entry_id'])
        if not entry_info:
            continue
        entry, chunk = entry_info
        mot = entry.get('mot', '')
        label_fr = entry.get('label_fr', '')
        if mot != label_fr:
            continue  # already translated

        defn = entry.get('definition', '').replace('\n', ' ').strip()
        suspects.append({
            'concept_id': cid,
            'label': label,
            'entry_id': primary['entry_id'],
            'chunk': chunk,
            'mot': mot,
            'def_preview': defn[:180],
        })

    suspects.sort(key=lambda s: s['mot'].lower())

    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUT_JSON, 'w', encoding='utf-8') as f:
        json.dump({'count': len(suspects), 'items': suspects}, f, ensure_ascii=False, indent=2)

    lines = [f'# Audit C9 — Category B (noms communs EN restants)', '',
             f'Total suspects : **{len(suspects)}**', '',
             '| mot | concept_id | entry_id | def_preview |',
             '|---|---|---|---|']
    for s in suspects:
        prev = s['def_preview'].replace('|', '\\|')[:120]
        lines.append(f"| **{s['mot']}** | `{s['concept_id']}` | `{s['entry_id']}` | {prev} |")
    with open(OUT_MD, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Suspects : {len(suspects)}')
    print(f'Output   : {OUT_JSON}')
    print()
    print('=== First 30 ===')
    for s in suspects[:30]:
        print(f"  {s['mot']:25s} {s['concept_id']:45s} {s['def_preview'][:80]}")


if __name__ == '__main__':
    main()
